// packages/react/src/components/AttachmentList.tsx
import type { CSSProperties, ReactNode } from 'react'
import type { AttachmentPart } from '@chat-composer/core'

export interface AttachmentListProps {
  attachments: AttachmentPart[]
  onRemove: (id: string) => void
  className?: string
  style?: CSSProperties
  renderItem?: (attachment: AttachmentPart, onRemove: () => void) => ReactNode
}

function formatBytes(bytes: number): string {
  if (bytes < 1024) return `${bytes} B`
  if (bytes < 1024 * 1024) return `${(bytes / 1024).toFixed(1)} KB`
  return `${(bytes / (1024 * 1024)).toFixed(1)} MB`
}

function UploadStatusIndicator({ status }: { status: AttachmentPart['uploadStatus'] }) {
  switch (status) {
    case 'uploading':
      return (
        <span style={{ fontSize: '0.7em', color: '#1976d2' }} title="Uploading...">
          ⏳
        </span>
      )
    case 'error':
      return (
        <span style={{ fontSize: '0.7em', color: '#d32f2f' }} title="Upload failed">
          ✗
        </span>
      )
    case 'uploaded':
      return (
        <span style={{ fontSize: '0.7em', color: '#388e3c' }} title="Uploaded">
          ✓
        </span>
      )
    default:
      return null
  }
}

export function AttachmentList({
  attachments,
  onRemove,
  className,
  style,
  renderItem,
}: AttachmentListProps) {
  if (attachments.length === 0) return null

  return (
    <div
      className={className}
      style={{
        display: 'flex',
        flexWrap: 'wrap',
        gap: 8,
        padding: '4px 0',
        ...style,
      }}
    >
      {attachments.map((att) => {
        const handleRemove = () => onRemove(att.id)
        if (renderItem) return renderItem(att, handleRemove)

        return (
          <div
            key={att.id}
            style={{
              display: 'inline-flex',
              alignItems: 'center',
              gap: 6,
              background: '#f5f5f5',
              borderRadius: 6,
              padding: '4px 8px',
              fontSize: '0.85em',
            }}
          >
            {att.type === 'image' && att.localUrl && (
              <img
                src={att.localUrl}
                alt={att.fileName}
                style={{
                  width: 32,
                  height: 32,
                  objectFit: 'cover',
                  borderRadius: 4,
                }}
              />
            )}
            {att.type === 'file' && <span style={{ color: '#666' }}>📄</span>}
            <span
              style={{
                maxWidth: 120,
                overflow: 'hidden',
                textOverflow: 'ellipsis',
                whiteSpace: 'nowrap',
              }}
            >
              {att.fileName}
            </span>
            <span style={{ color: '#999', fontSize: '0.85em' }}>{formatBytes(att.sizeBytes)}</span>
            <UploadStatusIndicator status={att.uploadStatus} />
            <button
              onClick={handleRemove}
              style={{
                border: 'none',
                background: 'none',
                cursor: 'pointer',
                color: '#999',
                fontSize: '0.9em',
                padding: '0 2px',
                lineHeight: 1,
              }}
              title="Remove"
            >
              ×
            </button>
          </div>
        )
      })}
    </div>
  )
}

// packages/vue/src/components/AttachmentList.vue
<script setup lang="ts">
import type { AttachmentPart } from '@chat-composer/core'

defineProps<{
  attachments: AttachmentPart[]
}>()

const emit = defineEmits<{
  remove: [id: string]
}>()

function formatBytes(bytes: number): string {
  if (bytes < 1024) return `${bytes} B`
  if (bytes < 1024 * 1024) return `${(bytes / 1024).toFixed(1)} KB`
  return `${(bytes / (1024 * 1024)).toFixed(1)} MB`
}
</script>

<template>
  <div v-if="attachments.length > 0" class="cc-attachment-list">
    <div
      v-for="att in attachments"
      :key="att.id"
      class="cc-attachment-item"
    >
      <slot name="item" :attachment="att" :on-remove="() => emit('remove', att.id)">
        <img
          v-if="att.type === 'image' && att.localUrl"
          :src="att.localUrl"
          :alt="att.fileName"
          class="cc-attachment-thumb"
        />
        <span v-if="att.type === 'file'" class="cc-attachment-icon">📄</span>
        <span class="cc-attachment-name">{{ att.fileName }}</span>
        <span class="cc-attachment-size">{{ formatBytes(att.sizeBytes) }}</span>
        <span
          v-if="att.uploadStatus === 'uploading'"
          class="cc-attachment-status cc-attachment-status--uploading"
          title="Uploading..."
        >⏳</span>
        <span
          v-else-if="att.uploadStatus === 'error'"
          class="cc-attachment-status cc-attachment-status--error"
          title="Upload failed"
        >✗</span>
        <span
          v-else-if="att.uploadStatus === 'uploaded'"
          class="cc-attachment-status cc-attachment-status--done"
          title="Uploaded"
        >✓</span>
        <button
          class="cc-attachment-remove"
          title="Remove"
          @click="emit('remove', att.id)"
        >×</button>
      </slot>
    </div>
  </div>
</template>

<style scoped>
.cc-attachment-list {
  display: flex;
  flex-wrap: wrap;
  gap: 8px;
  padding: 4px 0;
}

.cc-attachment-item {
  display: inline-flex;
  align-items: center;
  gap: 6px;
  background: #f5f5f5;
  border-radius: 6px;
  padding: 4px 8px;
  font-size: 0.85em;
}

.cc-attachment-thumb {
  width: 32px;
  height: 32px;
  object-fit: cover;
  border-radius: 4px;
}

.cc-attachment-icon {
  color: #666;
}

.cc-attachment-name {
  max-width: 120px;
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
}

.cc-attachment-size {
  color: #999;
  font-size: 0.85em;
}

.cc-attachment-status {
  font-size: 0.7em;
}

.cc-attachment-status--uploading {
  color: #1976d2;
}

.cc-attachment-status--error {
  color: #d32f2f;
}

.cc-attachment-status--done {
  color: #388e3c;
}

.cc-attachment-remove {
  border: none;
  background: none;
  cursor: pointer;
  color: #999;
  font-size: 0.9em;
  padding: 0 2px;
  line-height: 1;
}
</style>
